# Generated by Django 2.1.5 on 2019-02-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.DecimalField(decimal_places=8,
                                      max_digits=20,
                                      null=True),
        ),
    ]
