# Generated by Django 2.1.5 on 2019-02-10 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='balance',
        ),
        migrations.AddField(
            model_name='instrument',
            name='credit_created_at_d',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='credit_expires_at_d',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='credit_interest_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_currency',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.DecimalField(decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='instrument_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_from', to='client_user.Instrument'),
        ),
        migrations.AlterField(
            model_name='order',
            name='instrument_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_to', to='client_user.Instrument'),
        ),
        migrations.AddField(
            model_name='balance',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_user.Instrument'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
