# Generated by Django 2.1.5 on 2019-02-16 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0002_auto_20190210_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_user.Currency')),
            ],
        ),
        migrations.RenameModel(
            old_name='Balance',
            new_name='InstrumentBalance',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rate',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='is_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instrument_from',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instrument_to',
        ),
        migrations.AddField(
            model_name='order',
            name='instrument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='instrument', to='client_user.Instrument'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AddField(
            model_name='fiatbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
