# Generated by Django 2.1.7 on 2019-04-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0002_order_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityHistory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=8)),
                ('created_at_dt', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField()),
                ('instrument',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     to='client_user.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPriceHistory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8,
                                              max_digits=20)),
                ('created_at_dt', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField()),
                ('instrument',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     to='client_user.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='PlacedAssetsHistory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=8)),
                ('created_at_dt', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField()),
                ('instrument',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     to='client_user.Instrument')),
            ],
        ),
    ]
