# Generated by Django 2.1.7 on 2019-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user',
         '0003_liquidityhistory_orderpricehistory_placedassetshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidityhistory',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='placedassetshistory',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
