# Generated by Django 2.1.5 on 2019-02-16 16:19

import client_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0003_auto_20190216_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[(client_user.models.InstrumentStatus('active'), 'active'), (client_user.models.InstrumentStatus('inactive'), 'inactive'), (client_user.models.InstrumentStatus('deleted'), 'deleted')], default=client_user.models.InstrumentStatus('active'), max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(client_user.models.OrderStatus('active'), 'active'), (client_user.models.OrderStatus('completed'), 'completed'), (client_user.models.OrderStatus('deleted'), 'deleted')], default=client_user.models.OrderStatus('active'), max_length=30),
        ),
    ]
