# Generated by Django 2.1.5 on 2019-02-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0004_auto_20190216_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creator',
            new_name='user',
        ),
    ]
