# Generated by Django 2.1.5 on 2019-02-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0005_auto_20190216_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
