# Generated by Django 2.1.5 on 2019-02-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0008_auto_20190216_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('COMPLETED', 'completed'), ('DELETED', 'deleted')], default='active', max_length=30),
        ),
    ]
